Search
graphistry/pygraphistry pull request #409
Opened 2022-10-11 01:04 UTC by silkspace

2022-10-11 19:08 UTC, silkspace commented
@lmeyerov let me know if there is anything that is needed

2022-10-12 04:02 UTC, lmeyerov requested changes
Super close! See inline comments!

- [ ] some missing docs
- [ ] a couple non-functional interfaces / unsafe memoization
- [ ] multilabel: maybe default on (opt-in to any col with lists? or not b/c it's slow?), and when it is opted-in, allow picking which cols vs all
- [ ] various prints that should be disabled / logger

2022-10-12 04:18 UTC, silkspace commented on graphistry/feature_utils.py
> +        multilabel: bool = False,
`multilabel` works for a column that is a list of lists, so by default, should be False. 
so for example `df = pd.DataFrame({'col': ["a, b, c", "b, c", "d"])`

```
df['mlb'] = df.col.apply(lambda x: x.split(', '))
g = graphistry.nodes(df)
g2 = g.umap(X=..., y=['mlb'], multilabel=True)
```

2022-10-12 04:19 UTC, silkspace commented on graphistry/constants.py
> +VERBOSE = True  # set to true for info, false for debug, None for none
oof yes

2022-10-12 04:28 UTC, silkspace commented on graphistry/feature_utils.py
> +        multilabel: bool = False,
In fact, perhaps I should add an `Exception` if `multilabel=True` on a column that is not list of list (currently would just error ungracefully)

2022-10-12 05:06 UTC, silkspace commented on CHANGELOG.md
> +* Featurization: support for dataframe columns that are list of lists -> multioutput targets
yes but only if we unpin dirty_cat and change it to v0.3.0

2022-10-12 21:22 UTC, silkspace commented on graphistry/text_utils.py
> +        if not hasattr(self, 'search_index'):
Fixed

2022-10-12 21:27 UTC, silkspace commented on graphistry/text_utils.py
> +        """NL-query and return dataframe of results
Done, thanks

2022-10-12 21:28 UTC, silkspace commented on graphistry/text_utils.py
> +        """NL-query and return dataframe of results
I added it in the main `def search(..)` function

2022-10-12 21:40 UTC, silkspace commented on graphistry/text_utils.py
> +        """Input a natural language query and return a graph of
Done

2022-10-12 23:38 UTC, merged