Add multiple algorithm support in compute_igraph
graphistry/pygraphistry pull request #436
Opened 2023-02-07 19:45 UTC by sky-2002

@silkspace , This PR tries to solve issue mentioned [here](https://github.com/graphistry/pygraphistry/issues/405). With this, multiple algorithms can be passed as a list to the `compute_igraph` function.

2023-02-08 04:03 UTC, lmeyerov commented
@sky-2002  see my comment on https://github.com/graphistry/pygraphistry/issues/405 wrt more usable signature

looks like lint/type errors, see ci . you can build & test locally

see https://github.com/graphistry/pygraphistry/blob/master/DEVELOP.md#run-local-tests-without-rebuild + look at the script for env vars you can set

2023-02-08 20:31 UTC, sky-2002 commented
Hello @lmeyerov , @silkspace , I have made the necessary changes for more usable signature, added code to support custom fieldnames as suggested by @DataBoyTX in #405 and added tests too. Let me know if anything needs to be changed.

2023-02-08 21:56 UTC, lmeyerov commented on graphistry/tests/plugins/test_igraph.py
> +        assert 'bt' in multiple1._nodes.columns
assert also `pr` & `coci`

2023-02-08 21:56 UTC, lmeyerov commented on graphistry/tests/plugins/test_igraph.py
> +        assert 'closeness' in multiple2._nodes.columns
assert also `pagerank`

2023-02-08 21:56 UTC, lmeyerov commented on graphistry/plugins/igraph.py
> +    # alg: str,
remove

2023-02-08 21:57 UTC, lmeyerov commented on graphistry/plugins/igraph.py
> +    alg: Union[str, List[Union[str, Tuple[str, dict]]], Dict[str, Union[str, Tuple[str,dict]]] ],
Add `** Example...` of the new forms

2023-02-08 21:59 UTC, lmeyerov requested changes
Getting there!

* See CI errors
* Can you add an example to `readme.md` of the new forms?
* Can you add to the changelog? 
* See inline review comments

2023-02-09 17:55 UTC, sky-2002 commented
> Getting there!
> 
> * See CI errors
> * Can you add an example to `readme.md` of the new forms?
> * Can you add to the changelog?
> * See inline review comments

For the changelog, will this be fine - "Multiple algorithm support for igraph" in the [Development] Added section.

2023-02-10 02:23 UTC, lmeyerov commented
Looks like the type checker needs help?

2023-02-10 20:25 UTC, sky-2002 commented
> Looks like the type checker needs help?

Well, tried to fix it, let's see.

2023-02-11 05:53 UTC, lmeyerov commented
Great. Did you try running the tests locally? Set the various env vars of interest to `=1` @ https://github.com/graphistry/pygraphistry/blob/master/DEVELOP.md#run-local-tests-without-rebuild

2023-04-30 21:38 UTC, closed without merging

2023-04-30 21:38 UTC, lmeyerov commented
We can revisit this when more cycles, closing for now