change register command to use markdown instead of HTML for databricks users to see login link
graphistry/pygraphistry pull request #527
Opened 2023-12-20 20:32 UTC by DataBoyTX

…HTML to allow viewing for databricks users

2023-12-20 20:33 UTC, lmeyerov commented
@DataBoyTX see ci fails

2023-12-20 20:34 UTC, lmeyerov commented on graphistry/pygraphistry.py
> +            display(Markdown(f'[new: Login SSO]({auth_url})"))
missing import? + ci fails

does  this work in both jupyter + databricks?

2023-12-20 20:36 UTC, lmeyerov commented on graphistry/pygraphistry.py
> +            display(Markdown(f'[new: Login SSO]({auth_url})"))
also, `old/:new:` seems kind of funny for the text label, i think that's just for testing

2023-12-21 22:08 UTC, lmeyerov commented on graphistry/pygraphistry.py
> +from IPython.display import DisplayObject, TextDisplayObject
this shouldn't be a top-level import as it'd break many installs; note the dynamic import once we've sniffed

2023-12-21 22:12 UTC, lmeyerov commented on graphistry/pygraphistry.py
> +        import markdown as md
i'm worried about using `markdown` package as an unmet dependency

2023-12-21 22:14 UTC, lmeyerov commented on graphistry/pygraphistry.py
> +            display(Markdown(f'[new: Login SSO]({auth_url})'))
should we split this to something like

```python
if in_ipython() or sso_opt_into_type=='display': ...
elif in_databricks() or sso_opt_into_type=='displayHTML': ...
else ...
```

and then we can use the right render for each?

also, should double check databricks notebooks vs dashboards

2023-12-21 22:15 UTC, lmeyerov requested changes
see comments

2024-01-16 13:14 UTC, lmeyerov commented
@vaimdev I think this is really 2 different issues:

1. Ensure in databricks + jupyter that the link immediately appears (vs after 30s) . That includes when used in a databricks dashboard view.

2. Respect overrides. User should be able to force a display mode, and sniffers should not override that decision if provided. Currently, databricks/python sniffers override any explicit decision.

2024-02-25 00:08 UTC, lmeyerov commented
is this closing in favor of https://github.com/graphistry/pygraphistry/pull/543 ?

2024-03-12 05:50 UTC, DataBoyTX commented
> is this closing in favor of #543 ?

yes

2024-03-12 06:07 UTC, lmeyerov commented on CHANGELOG.md
> +>>>>>>> 2506b798ec723e906c1c5279f613fe0c37bdbad2
@DataBoyTX bad merge?

2024-03-12 06:12 UTC, lmeyerov commented on graphistry/pygraphistry.py
> +        except Exception:  # required to log on
can we be selective on the Exception for the one we expect to be thrown?

2024-03-12 06:13 UTC, lmeyerov commented on graphistry/pygraphistry.py
> +    def databricks_notebook_sso_login(
is this for databricks notebooks or databricks dashboards?

Where in dashboards, I think the idea is first cell is a non-blocking print, and second cell is a blocking poll on successful sso

Where in notebooks... ?

2024-03-12 06:16 UTC, lmeyerov commented on graphistry/pygraphistry.py
> +        **Example: Databricks notebook and dashboard users need to call the following before register to correctly display the HTML link:
I think in the dashboard case, it needs to be in 2 different cells, one is a non-blocking url print, and the other the blocking register for whichever cell will plot

I'm not sure what's needed, if anything,  for notebooks?

2024-03-12 06:18 UTC, lmeyerov commented on graphistry/pygraphistry.py
> +                print("Please close browser tab after SSO login to back to notebook")
mixing `display()` and `print()` suggests an incomplete case analysis & handling, can we handle more carefully?

2024-03-12 18:51 UTC, lmeyerov commented on graphistry/pygraphistry.py
> +            if auth_url and not PyGraphistry.api_token():
in the notebook case (but not needed in dashboard), we risk having an expired token (e.g., been up for an hour)

normally there's an auto-refresh that kicks in for some of the dispatched methods, so this gets auto-handled at plot

BUT when an explicit public call like this one, it makes sense to show the url either way, or to make this an option?

2024-03-12 18:53 UTC, lmeyerov commented on graphistry/pygraphistry.py
> +            if in_ipython() or sso_opt_into_type == 'display':  # If run in notebook, just display the HTML
let's make sure overrides get followed before sniffers, so sniffers don't supercede them

2024-03-12 18:54 UTC, lmeyerov commented on graphistry/pygraphistry.py
> +                print("Please close browser tab after SSO login to back to notebook")
we can make print() vs display() options, and sniffers pick the right one

2024-12-19 04:01 UTC, closed without merging